---
title: "PCA plots for identification of outliers to prune from the dataset"
output: html_document
date: "2024-03-01"
---

# Setting up the Working Directory of the .rmd script
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Defining the relative path in the repository
repository_path <- "/Computational-modelling-of-genomic-inbreeding-and-roh-islands-in-extremely-small-populations"

# Set the path to your GitHub folder
YOUR_GITHUB_ROOT_DIRECTORY <- "C:/Users/jonat/GitHub"

# Set the root directory for notebook chunks
knitr::opts_knit$set(root.dir = file.path(YOUR_GITHUB_ROOT_DIRECTORY, repository_path))


# # Verify the current working directory
# getwd()

```

# PCA Plots
Plots are created both for the preprocessed and the raw datasets

```{r PCA_Plot}
# Load the MASS package for fitdistr function
library(MASS)

# Read the data
data <- read.table("sorted_population_coverage.bed", header = FALSE)

# Assuming your data is in the fourth column
values <- data$V4

# Sort the values in descending order to find the top 1%
sorted_values <- sort(values, decreasing = TRUE)

# Calculate the threshold for the top 1%
threshold_index <- ceiling(0.05 * length(sorted_values))
threshold <- sorted_values[threshold_index]

# Identify genomic windows with ROH frequency above the threshold
top_5_percent_ROH <- data[data$V4 > threshold, ]

# Print the top 1% of ROH regions
print(top_5_percent_ROH)







```