---
title: "GONE_Empirical_Ne_estimation"
output: html_document
date: "2024-06-18"
---


# 0: Preparation
Defining the input and output files

```{r setup,echo = FALSE}
# Clean the working environment
rm(list = ls())

# Set the path to your GitHub folder
YOUR_GITHUB_ROOT_DIRECTORY <- "C:/Users/jonat/GitHub"

# Defining the relative path in the repository
repository_path <- file.path(YOUR_GITHUB_ROOT_DIRECTORY,"Computational-modelling-of-genomic-inbreeding-and-roh-islands-in-extremely-small-populations")



GONE_results_dir <- file.path(repository_path)
# GONE_results_dir <-  Sys.getenv("GONE_results_dir")
empirical_data_prefix <- "german_shepherd_filtered"
# empirical_data_prefix <-  Sys.getenv("empirical_data_prefix")

N_e_results_file <- paste0("Output_Ne_",empirical_data_prefix)




```

## Loading Libraries
```{r Loading libraries, include=FALSE}

# library(dplyr)
# library(readr)
library(ggplot2)
```

## Results
```{r N_e results}

setwd(GONE_results_dir)
N_e_results <- read.table(N_e_results_file, header = TRUE, comment.char = "#", stringsAsFactors = FALSE, sep = "\t", skip=1)


Estimated_N_e_empirical_data <- N_e_results$Geometric_mean[1]
cat("Estimated current effective population size:", round(Estimated_N_e_empirical_data,0))
# View(N_e_results)
```
# Plotting the results
```{r}
N_e_estimation_during_breed_formation <- N_e_results[N_e_results$Generation <= 40, ]
# Create the plot
plot <- ggplot(N_e_estimation_during_breed_formation, aes(x = Generation, y = Geometric_mean)) +
  geom_line(color = "blue") +  # Add a line plot
  geom_point(color = "red") +  # Add points to the plot
  labs(title = "N_e estimation during breed formation",
       x = "Generation",
       y = "Geometric Mean of Effective Population Size") +
  theme_minimal()  # Use a minimal theme for a clean look

# Display the plot
print(plot)
```


```{r}
# Create the plot
plot <- ggplot(N_e_results, aes(x = Generation, y = Geometric_mean)) +
  geom_line(color = "blue") +  # Add a line plot
  geom_point(color = "red") +  # Add points to the plot
  labs(title = "GONE estimation of N_e Over Generations",
       x = "Generation",
       y = "Geometric Mean of Effective Population Size") +
  theme_minimal()  # Use a minimal theme for a clean look

# Display the plot
print(plot)
```

